/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.aot;

public class App {
    public static long fib(int n) {
        if (n <= 1) return n;
        return fib(n-1) + fib(n-2);
    }

    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        long result = fib(40);
        long end = System.currentTimeMillis();
        System.out.println("Fib(40) = " + result);
        System.out.println("Elapsed time: " + (end - start) + " ms");
    }
}
